# Generated by Django 6.0.6 on 2026-07-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/')),
                ('nomi', models.CharField(max_length=50)),
                ('narxi', models.IntegerField()),
                ('skidka', models.IntegerField()),
            ],
        ),
    ]
