# Generated by Django 6.0.6 on 2026-07-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uzum', '0002_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_aksiya',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_arzonlashdi',
            field=models.BooleanField(default=False),
        ),
    ]
