# Generated by Django 6.0.7 on 2026-07-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uzum', '0003_product_is_aksiya_product_is_arzonlashdi'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tavsif',
            field=models.TextField(null=True),
        ),
    ]
