# Generated by Django 6.0.7 on 2026-07-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uzum', '0004_product_tavsif'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
