# Generated by Django 6.0.7 on 2026-07-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uzum', '0005_product_img1_product_img2_product_img3_product_img4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img5',
        ),
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
