# Generated by Django 6.0.7 on 2026-07-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uzum', '0006_remove_product_img4_remove_product_img5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img3',
        ),
    ]
